const General = {
    HOME:"Home",
    ABOUT:"About",
    LOGOUT:"Log Out",
    USERNAME:"Username",
    PASSWORD:"Password",
    EMAIL:"Email",
    LOGIN:"Log In",
    SIGNUP:"Sign Up",
    SUBMIT:"Submit",
    DASHBOARD:"Dashboard",
    FAVORITE:"Favorite",
    PROFILE:"Profile",
    INPUT_CITY_TITLE:"City",
    INPUT_TEMPERATURE_TITLE:"Available Unit",
    INPUT_DARK_MODE_TITLE:"Use Dark Mode",
    INPUT_SAVE:"SAVE",
    BACKTOLOGIN:"Back To Log In",
    TITLELOGIN:"Welcome To Recipe Explorer",
    WRONGINPUTLOGIN:"Wrong username or password!",
    EXPLORERECIPE_TITLE:"Explore Recipe",
    SEARCH:"Search",
    DETAIL:"Detail",
    CLOSE:"Close",
    EMPTY_FAVORITE_MESSAGE:"There no favorite recipe yet.",
    RESULT_SEARCH:"Result search 10 from total",
    UPDATE:"Update",
    SIGNUP_TOBE_MEMBER:"Sign Up To Be Member",
    SIGNUP_WRONG_INPUT:"Wrong format username or password or email!",
    DETAIL_RECIPE_PLEASE_WAIT:"Please wait, data is being fetching",
    FAVORITE_CONFIRMATION:"{titleRecipe} get favorited.",
    FAVORITE_TITLE:"Favorite Menu",
    DELETE_ACCOUNT:"Delete Account",
    DELETE_ACCOUNT_CONFIRMATION_TITLE:"Delete Confirmation",
    DELETE_ACCOUNT_CONFIRMATION_TEXT:"Are you sure delete this account {username}?",
    DELETE_ACCOUNT_YES_BTN:"Yes, delete this account",
    DELETE_PROCESS_TITLE:"Delete",
    DELETE_PROCESS_TEXT:"Data is being deleted. Please wait.",
    LOGIN_AS_GUEST:"Log In As Guest (demo)",
    PROFILE_WAIT_MESSAGE: "Please wait, your request already in process.",
  };
  
  export default General